### ISSUE TITLE
installation and configuration of ChartJS 

### ISSUE THREAD

**Issue by PhilLAL** [luciozambon/eGiga2m#10]
Hi,
following #5 I saw that several commits have been made in repo 24 days ago about chartjs, especially creation of chartjs directory.

Do you have some instructions about how to install this ChartJS and how to configure it?
Regards

**Comment by luciozambon** [comment]
instructions are unchanged
https://github.com/luciozambon/eGiga2m/blob/master/INSTALL.md
if you already have a working installation, you can try to install in a new
folder test it and when it's all OK you should remove the old installation
and rename the new one with the old name

**Comment by PhilLAL** [comment]
Thank you.

I installed the master in a new `/var/www/html` directory and copied into it ̀`egiga2m_conf.js` and `lib/service//hdb_conf.php` to use the same configuration.

However, I got this error in console:
```
Uncaught ReferenceError: isHighChartsInstalled is not defined
    <anonymous> http://HOSTNAME.DOMAINNAME.fr/eGiga2m-1.16.3/egiga2m.min.js:6
```

**Comment by luciozambon** [comment]
you could add in egiga2m_conf.js
var isHighChartsInstalled = 0;

**Comment by PhilLAL** [comment]
It works now.It works, thank you.:)
