### ISSUE TITLE
display with min & max defined 

### ISSUE THREAD

**Issue by PhilLAL** [luciozambon/eGiga2m#4]
Hi Lucio,
we use `flot.js` for display in eGiga2m and when we let `Config` panel with default parameters, plot displays correctly, as followed (please note min & max values in left scale axis):
![screenshot](https://owncloud.lal.in2p3.fr/index.php/s/COIGv7F2Z30HvlE/download)

When we configure `Config` panel with min value, max value, or min & max values, a waiting wheel displays and no plot appears.
This occurs whatever the min value (resp. max) is lesser than the minimal value which displays in the plot scale (on the left axis) as follows :

![screenshot](https://owncloud.lal.in2p3.fr/index.php/s/3XyCw2tR5mBkxtG/download)

![screenshot](https://owncloud.lal.in2p3.fr/index.php/s/hGgajzFdINOCtnB/download)

If `Show time series data in a table` is checked in `Config`panel, the table displays.

If we erase the value entered in min and/or max, the plot displays.

Do you have any idea how to solve this?
Thank you

**Comment by PhilLAL** [comment]
Hi @luciozambon
this problem is really a pain in the ass for our users since they cannot see their data.
Do you have any idea of a workaround if no solution exists in short term?
Thank you

**Comment by luciozambon** [comment]
I did a bugfix on egiga2m.js and egiga2m.min.js
now you shouldn't go into infinite loop, but the management of max and min by flot seems poor.
If I had enough time I would substitute flot with something like https://webgl-plot.vercel.app/ or https://www.chartjs.org/
Any volonteer?

**Comment by PhilLAL** [comment]
It works, thank you very much for this fast patch :)

However, I am sorry but I would not have the skills to replace flot by another tool.
