### ISSUE TITLE
use of X axis

### ISSUE THREAD

**Issue by PhilLAL** [luciozambon/eGiga2m#5]
Hi @luciozambon,
I noticed 2 issues while displaying on X axis :

1. X axis does display more than 7 days. I did not find anything about that in the doc.

2. when using minmax and "Igrore values over Max and below Min", display reset X axis to 17h-24h current day while displaying up left start and stop selected timestamp in date fields (in my case 2021-09-10 00:00:00 and 2021-09-16 00:00:00) and "eGiga2m - 2021-09-10 00:00:00 - 2021-09-16 00:00:00" up left in the figure.

Is it normal behaviour? 
Thank you

**Comment by PhilLAL** [comment]
Hi @luciozambon
ping just to confirm you confirm this is not my misunderstanding, or if by chance there is a workaround...
Thank you

**Comment by luciozambon** [comment]
In the docs there is an example "7 days" but in the calendar you can pick
some intervals between 5 minutes to 10 years, Furthermore you can specify
any integer number before minutes, hours, days, months, years.

The second issue is flot related, there is no problem with HighChart, Max
and min have a very limited support in flot, I've already written that the
real solution would be to use another chart library

**Comment by PhilLAL** [comment]
Thank you @luciozambon 

I am not skilled in js to do more than basic fixes.

I understand from answer 2 that Flot should not be considered as solution and HighCharts is the only chart library available for eGiga2m. Perhaps some focused warning should be added in documentation about this?

**Comment by luciozambon** [comment]
Ok ti add some warning in doc.
Anyway now there is one more option.
It is chartjs. I Hope this Will completely replace flot. By now I've
declared flot Legacy. Perhaps I Will declare It deprecated

**Comment by PhilLAL** [comment]
Is it implemented yet?
Do you have any information which would help me test ChartJS? 
Currently, I only see Flot Charts and HighCharts on [doc](https://luciozambon.altervista.org/egiga2m/doc/index.html)
Regards

**Comment by luciozambon** [comment]
It is implemented, but it isn't not in the doc yet

**Comment by luciozambon** [comment]
I've updated the doc
https://luciozambon.altervista.org/egiga2m/doc/index.html
https://github.com/luciozambon/eGiga2m/blob/master/doc/index.html

**Comment by PhilLAL** [comment]
Thank you :)
FYI, https://luciozambon.altervista.org/egiga2m/doc/index.html seems not up-to-date since it still displays 2 libraries (`Two graphic library are supported: Flot Charts has MIT licence; Highcharts offers more features.`)

**Comment by luciozambon** [comment]
I think that "Two graphic library ..." is in your browser cache

**Comment by PhilLAL** [comment]
it's ok now!

**Comment by PhilLAL** [comment]
Trying again the new 1.16.3 version, I got the same error about reseting time set:

Config:
- start: 2021-08-26 00:00:00
- stop: 2021-09-16 00:00:00

Result:
you see down left that first timestamp is not 26/08/2021 but 10/9/2021
  
![snapshot with start time reset while clicking on show](https://owncloud.lal.in2p3.fr/index.php/s/tJtOk9bfEUw04Mz/download)

Do you have any idea why?

**Comment by luciozambon** [comment]
ad idea is that time series XLI/OP/TMD.01/l1 and XLI/OP/TMD.01/l4 have no
data between 26/08/2021 and 10/09/2021
this can be monitored exporting data in JSON format, or show data in table

otherwise the decimation algorithm can be faulty
this can be checked changing the time interval

**Comment by PhilLAL** [comment]
You're right, it was the first solution which applied: chartJS seems to change time set to adapt to an interval in which data are available.

Thank you for your help!
