### ISSUE TITLE
display min & max with 2 axes

### ISSUE THREAD

**Issue by PhilLAL** [luciozambon/eGiga2m#8]
Hi @luciozambon,
it seems min & max only apply to Y1.
eGiga2m allows displaying 2 axes which is interesting functionnality, but it does not seem to allow defining min & max for Y2. Di you confirm?
Is there another way to define min & max for Y2, or is it possible to add something to allow this?

Thank you.

**Comment by PhilLAL** [comment]
I add 2 screenshot to illustrate my issue

![screenshot](https://owncloud.lal.in2p3.fr/index.php/s/5ssPiRYVUJonPrx/download)
![screenshot](https://owncloud.lal.in2p3.fr/index.php/s/V6yB8EQm5Cgiz5i/download)

We see Y1 axis is between 0 and 3500 and Y2 is between -1 and +1 instead of 0-5000 for Y1 and 0-7000 for Y2 as defined in Config

**Comment by luciozambon** [comment]
I partially confirm.
I mean this is an issue only with flot, it isn't an issue with HighCharts.

**Comment by PhilLAL** [comment]
Thank you @luciozambon it works!

To allow other users to check what it looks like, here is a snapshot 
![eGiga2m min-max on 2 axes](https://owncloud.lal.in2p3.fr/index.php/s/JYlPfvs42jaU063/download)
