### ISSUE TITLE
export "not available jet"

### ISSUE THREAD

**Issue by PhilLAL** [luciozambon/eGiga2m#9]
Hi @luciozambon,
while trying to export, I noticed that export is not available and display a link to "not available jet"
![screenshot](https://owncloud.lal.in2p3.fr/index.php/s/JykDpz5DrB6VNO7/download)

I'm pretty sure I used export since I answered a colleague how to export data  december, 24th 2020. 

I checked the source code and this string appears in https://github.com/luciozambon/eGiga2m/blob/6b01e1218b39b748d3a9af15cd0b599b3a57c2f1/egiga2m.html around line 247
Since this content did not change last 3 years, I think this could be a configuration issue, so I checked  
`egiga2m_conf.js` but it seems correct:
```
function initConf(conf) {
        // hcExportService = "http://ecsproxy.elettra.trieste.it:8080/highcharts-export-web/";
        if (conf=='HDB') {
                plotService = "./lib/service/hdb_plot_service.php?conf=HDB";
                treeService = "./lib/service/hdb_tree_service.php?conf=HDB";
                exportService = "./lib/service/hdb_export_service.php?conf=HDB"
        }
        else if (conf=='TDB') {
                plotService = "./lib/service/hdb_plot_service.php?conf=TDB";
                treeService = "./lib/service/hdb_tree_service.php?conf=TDB";
                exportService = "./lib/service/hdb_export_service.php?conf=TDB"
        }
        else {
        // this is the default configuration, comment it if unnecessary
        plotService = "./lib/service/hdb_plot_service.php?conf=HDB";
        treeService = "./lib/service/hdb_tree_service.php?conf=HDB";
        exportService = "./lib/service/hdb_export_service.php?conf=HDB"; // please switch hdb_export_service with hdbpp_export_service if necessary
        }
```

I'm pretty sure this is a silly error, do you mind helping me with this?
Thank you,

**Comment by luciozambon** [comment]
There are two type of export:
Image or data.
Image export depends on the chart library, flot supports only one format.
For data export you must select time and variable first.
JSON export is particolar because It exposes exactly the same source of
data used for the plot. So this is the first experiment to be done in a
debug session.

**Comment by PhilLAL** [comment]
Thank you for this fast answer.
I would like to export data. 
I selected time (we see it up left in background) and attribute (left in background). 
I do not understand what i forgot in light of your explanations.

**Comment by luciozambon** [comment]
can you access

"./lib/service/hdb_plot_service.php?conf=HDB" and
"./lib/service/hdb_tree_service.php?conf=HDB"?

you should substitute "./" with your server

**Comment by PhilLAL** [comment]
yes, they seem accessible.

Here are the output: 
- for ./lib/service/hdb_plot_service.php?conf=HDB 
![screenshot for ./lib/service/hdb_plot_service.php?conf=HDB](https://owncloud.lal.in2p3.fr/index.php/s/p4HsZU9sW8nnSSH/download)
- ./lib/service/hdb_tree_service.php?conf=HDB
![screenshot for ./lib/service/hdb_tree_service.php?conf=HDB](https://owncloud.lal.in2p3.fr/index.php/s/Qc0VDi1fhPHq5aE/download)

**Comment by luciozambon** [comment]
sorry, you should check the export service, in the default egiga2m_conf.js
there is this row:

exportService = "./lib/service/hdb_export_service.php?conf="; // please
switch hdb_export_service with hdbpp_export_service if necessary

**Comment by PhilLAL** [comment]
I replace it by those lines:
- if: `exportService = "./lib/service/hdb_export_service.php?conf=HDB"`
- then: `exportService = "./lib/service/hdb_export_service.php?conf=TDB"`
- else: `exportService = "./lib/service/hdb_export_service.php?conf=HDB"; // please switch hdb_export_service with hdbpp_export_service if necessary`

**Comment by PhilLAL** [comment]
Do you see any error which could explain my issue?

**Comment by luciozambon** [comment]
the if condition should have a comparison (e.g. a==b) not an assignment
(e.g. a=b)
in this configuration file you should only place the right link for your
installation

you should test something like this:
srv-6.thomx.fr/eGiga2m/lib/service/hdbpp_plot_service.php?conf=HDB&start=last
8 hours&stop=&ts=3

**Comment by PhilLAL** [comment]
Thank you for your answer, i was not clear in my answer.

I replace default lines by those lines:
- in if statement : `exportService = "./lib/service/hdb_export_service.php?conf=HDB"`
- in then statement : `exportService = "./lib/service/hdb_export_service.php?conf=TDB"`
- in else statement: `exportService = "./lib/service/hdb_export_service.php?conf=HDB"; // please switch hdb_export_service with hdbpp_export_service if necessary`

Indeed, test in if are of course `==` and not assignement `=`

Here is the complete if statement:
```
        if (conf=='HDB') {
                plotService = "./lib/service/hdb_plot_service.php?conf=HDB";
                treeService = "./lib/service/hdb_tree_service.php?conf=HDB";
                exportService = "./lib/service/hdb_export_service.php?conf=HDB"
        }
        else if (conf=='TDB') {
                plotService = "./lib/service/hdb_plot_service.php?conf=TDB";
                treeService = "./lib/service/hdb_tree_service.php?conf=TDB";
                exportService = "./lib/service/hdb_export_service.php?conf=TDB"
        }
        else {
        // this is the default configuration, comment it if unnecessary
        plotService = "./lib/service/hdb_plot_service.php?conf=HDB";
        treeService = "./lib/service/hdb_tree_service.php?conf=HDB";
        exportService = "./lib/service/hdb_export_service.php?conf=HDB"; // please switch hdb_export_service with hdbpp_export_service if necessary
        }
```

**Comment by PhilLAL** [comment]
Hi @luciozambon 
since the file content seems OK, do you see what can make this fail?
Cheers

**Comment by luciozambon** [comment]
Have you tested something like this?
srv-6.thomx.fr/eGiga2m/lib/service/hdb_export_service.php?conf=HDB&start=last
8 hours&stop=&ts=3

**Comment by PhilLAL** [comment]
I tested it, indeed, and it worked as soon as I select an archived attribute.
However, clicking on "Export" menu still displayed the same "not available jet" message.

**Comment by luciozambon** [comment]
may be there is something wrong in
exportService = "./lib/service/hdb_export_service.php?conf=HDB"
in order to monitor actual value of  exportService  you can open the
console of the browser (
https://developer.mozilla.org/en-US/docs/Tools/Browser_Console ) and type:
exportService

**Comment by PhilLAL** [comment]
I get `exportService
"http://thomx-srv-6.DOMAINNAME.fr/eGiga2m/lib/service/hdb_export_service.php?conf=HDB"`
(where DOMAINNAME is a redirect and thomx-srv-6 is the hostname known from the network in which I am connected)

**Comment by luciozambon** [comment]
you could try to change exportService with
srv-6.thomx.fr/eGiga2m/lib/service/hdb_export_service.php?conf=HDB

**Comment by PhilLAL** [comment]
It's strange since it does not work with current production instance, but the new instance works with export.

Since `egiga_conf.js` and `lib/service/hdb_conf.php` are the same in both instances, my understanding is the error is probably in other modifications recenlty done, am I wrong?

**Comment by luciozambon** [comment]
If I were in your institute the debug probably would be a matter of no more
than 5 minutes
In this situation it's much complicated

**Comment by PhilLAL** [comment]
after exchanging by webconf, these changes fix it:
in `egiga2m.html`: 
- replace `<script src='./egiga2m.min.js' type="text/javascript"></script>` by `<script src='./egiga2m.js' type="text/javascript"></script>`
In `egiga2m.min.js`:
- comment lines 327, 408, and 413 :
```
327c327
< 			document.getElementById('timestamp').setAttribute("onChange","javascript: refreshExportLink();");
---
> 			//document.getElementById('timestamp').setAttribute("onChange","javascript: refreshExportLink();");
408c408
< 		document.getElementById("timestampBlock").style.display = 'inline';
---
> 		//document.getElementById("timestampBlock").style.display = 'inline';
413c413
< 		exportTsLabel = exportTsLabel + (document.getElementById('timestamp').checked? '&timestamp': '');
---
> 		//exportTsLabel = exportTsLabel + (document.getElementById('timestamp').checked? '&timestamp': '');
```
